### ISSUE TITLE
Serious Problems in iOS

### ISSUE THREAD

**Issue by trans** [martec/quickadveditorplus#10]
On iOS devices, the edit field doesn't word wrap, sometimes the cursor jumps back to the home position and there is a huge lag in performance -- you'll be typing and nothing will show up and then suddenly all the characters appear.

I've updated to all the latest releases (MyBB and Quick Advance Editor Plus), but still the issue persists.

**Comment by martec** [comment]
Sorry but i can't fix issue related with sceditor....
