### ISSUE TITLE
Quick AEP breaks links to posts in source mode

### ISSUE THREAD

**Issue by wizard974** [martec/quickadveditorplus#11]
Steps to reproduce :

1.  Tick in User CP > Edit Options > Put the editor in source mode by default
2.  Open an active thread or follow a direct link to a post

It jumps directly at the bottom, into the Quick Reply and not into the posts.

**Comment by martec** [comment]
this isn't related with my plugin
http://community.mybb.com/thread-160306-post-1165625.html#pid1165625

you can set to load editor when clicking inside the text area:

http://community.mybb.com/thread-158367-post-1192011.html#pid1192011
