### ISSUE TITLE
Javascript error when setting for source mode editor is true but show quick reply box is false

### ISSUE THREAD

**Issue by lairdshaw** [martec/quickadveditorplus#16]
The Javascript error

> TypeError: MyBBEditor.sourceMode is not a function

is encountered, as seen in the browser's console on pressing F12 and loading a thread view page, when the Options in the User Control Panel are as follows:

- "Put the editor in source mode by default" => checked
- "Show the quick reply box on the view thread page." => unchecked

This error can be avoided by changing line 1100 of inc/plugins/quickadveditorplus.php from:

`		if($mybb->user['sourceeditor'] == 1)`

to:

`		if($mybb->user['sourceeditor'] == 1 && $mybb->user['showquickreply'] == 1)`

That is: let's not try to set the source mode when there's no editor there in the first place.

**Comment by martec** [comment]
thanks...
i will add this code above in next version...
