### ISSUE TITLE
Show CAPTCHA for quick replay form

### ISSUE THREAD

**Issue by rezapori** [martec/quickadveditorplus#17]
Hi,
We need to enable MyBB default captcha image for quick reply form, in MyBB configuration use captcha for post is enable but not show in "quickadveditorplus plugin".
I install [captcha plugin](https://community.mybb.com/mods.php?action=view&pid=323) and config it but not show any thing ... .
Plz help me to enable captcha in quick reply form.
thanks a lot.

**Comment by martec** [comment]
sorry but i can't to do anything....
you need ask to captcha plugin developer...
