### ISSUE TITLE
Quick quote "Reply" box doesn't pop-up on Firefox when dragging selection outside of post

### ISSUE THREAD

**Issue by lairdshaw** [martec/quickadveditorplus#18]
On Firefox, when selecting, it is possible to let go of the mouse button outside of the post content, without (as on Chrome) non-post content being selected. In this case, the user expects that the "Reply" link will pop up as usual since only content from within the post is selected, but it doesn't.

I've reworked `Thread.quickquote.js` so that it handles this situation, and in recent testing it seems to work without problem on both Firefox and Chrome, although I seem to remember that a little while back it occasionally would also fail to pop up the "Reply" link, so it could probably do with a bit of testing by others.

If you like, I'll create a PR for this, or otherwise just let me know how to share the file with you.

**Comment by lairdshaw** [comment]
> If you like, I'll create a PR for this

Well, whether you like it or not, I've done that...

**Comment by martec** [comment]
Thanks for PR...
I haven't tested it but I will accept the PR. In the future, if this causes other problems, it can be undone.
Thanks again for sharing.
